### PR TITLE
Added in a retrieval function for the tables containing financial data.

### PR DESCRIPTION
**Pull request by dxlnr**
Added a `retrieve_html_tables` function in `extract_items` to retrieve all the tables containing financial data as pandas dataframes. This can be used to store them in a csv or similar file format.

### CODE REVIEW

**Comment by eloukas** [comment]
Hi @dxlnr, thanks for the pull request! 👋 
Indeed, this is something that people are interested in. Before merging it, we need to see how well it works.

Could you provide the output result for some (e.g., 4 or 5) reports of different companies' reports?
(I am asking this because tables structure might change between different years and different companies).

For example, you could copy/paste (or screenshot) the relevant table in the report, and then the code's output.
For reproduction purposes, it would be good to also say which report is that, so I can reproduce it, before merging it into the codebase.

Once again, many thanks for the contribution 🙌

**Comment by dxlnr** [comment]
Hi! I added two more commits, with minor fixes and a testing pipeline for retrieving the tables. Please find the results in the `tests/fixtures/EXTRACTED_TABLES.zip`. I used the `AMD` filings of 2017 and 2022 and kept the table extraction separate from the raw `text/json` extraction. I decided to create one `csv` file for all table from a single filing. Maybe there is a better solution for collecting these tables. (Problem is that they have different column numbers throughout).

**Comment by dxlnr** [comment]
Screenshot from 2023-11-19 18-08-50
Only issue that remains is that the table rows with blank space like the one in the image (**Diluted** & **Basic**). Gets extracted with 
,,Basic,952,952,835,835
,,Diluted,"1,039",952,835,835
Which is somewhat wrong.

**Comment by dxlnr** [comment]
Other than that, I created an additional function `extract_tables` in `extract_items.py` to make it testable. This function used parts of the `extract_items` function which might be fused in the future to avoid duplicated code.

**Comment by dxlnr** [comment]
@eloukas Can I help along with any issues to get it merged eventually?

**Comment by eloukas** [comment]
Hi @dxlnr and sorry for the late response -- I was not working on EDGAR-CRAWLER for the past months.

Now, I am adding some other, but higher priority, functionalities to the repo, along with one other collaborator (aka support for 8-k docs in item extraction).
The extract_items.py is getting rewritten so some conflicts should be resolved there, in case you are still interested in contributing that retrieval function. I am closing the PR (at least temporarily, since I know, many months passed), but feel free to reopen it if you want it to get merged in the *current* version. This way, we can discuss again how and where to store the results.

**Pull request closed without merging**
